// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriCore.Data;

#nullable disable

namespace NutriCore.Data.Migrations
{
    [DbContext(typeof(NutriCoreContext))]
    [Migration("20251025182152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutriCore.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("float");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fats")
                        .HasColumnType("float");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kilocalories")
                        .HasColumnType("int");

                    b.Property<int>("MeasurementQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Proteins")
                        .HasColumnType("float");

                    b.Property<double>("Salt")
                        .HasColumnType("float");

                    b.Property<double>("Sugar")
                        .HasColumnType("float");

                    b.Property<int>("UnitOfMeasurement")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Carbohydrates = 0.0,
                            CreatedBy = "Admin",
                            Fats = 91.0,
                            Image = "https://www.google.com/url?sa=i&url=https%3A%2F%2Ffinditapp.es%2Fproduct%2F21545%2Faceite-de-oliva-virgen-extra-hacendado&psig=AOvVaw3lJleOAYGiYoGiu_nXPnVO&ust=1761502309066000&source=images&cd=vfe&opi=89978449&ved=0CBUQjRxqFwoTCPDws8_5v5ADFQAAAAAdAAAAABAE",
                            Kilocalories = 822,
                            MeasurementQuantity = 100,
                            Name = "Aceite de oliva virgen extra Hacendado",
                            Proteins = 0.0,
                            Salt = 0.0,
                            Sugar = 0.0,
                            UnitOfMeasurement = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Carbohydrates = 4.5999999999999996,
                            CreatedBy = "Admin",
                            Fats = 3.6000000000000001,
                            Image = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fsuper.facua.org%2Fmercadona%2Fleche%2Fleche-entera-hacendado-1-l%2F&psig=AOvVaw3kHUfgmwIYi6NkahqgqyVE&ust=1761502634457000&source=images&cd=vfe&opi=89978449&ved=0CBUQjRxqFwoTCPCF0Or6v5ADFQAAAAAdAAAAABAE",
                            Kilocalories = 63,
                            MeasurementQuantity = 100,
                            Name = "Leche entera Hacendado",
                            Proteins = 3.1000000000000001,
                            Salt = 0.13,
                            Sugar = 4.5999999999999996,
                            UnitOfMeasurement = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("NutriCore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 1,
                            Country = "España",
                            Email = "admin@nutricore.com",
                            Height = 30,
                            Name = "Admin",
                            Password = "YHrp/ExR53lRO6ouA2tT0y9QCb94jfjNBsxcGq5x798=",
                            Role = "admin",
                            Weight = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 24,
                            Country = "España",
                            Email = "mario@gmail.com",
                            Height = 170,
                            Name = "Mario",
                            Password = "JApd9lfG2wshq3agTXjgwVT/f4jQecLCYTBnBT30AqE=",
                            Role = "user",
                            Weight = 65
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
